Cover image for Como adicionar o Snake Game no seu README do Github ğŸ
Karol
Karol
Posted on Mar 29, 2023


4
Como adicionar o Snake Game no seu README do Github ğŸ
#
github
#
tutorial
[Atualizado 2023]
Passo 1: Criando o RepositÃ³rio
A primeira coisa que vocÃª deve fazer Ã© criar um repositÃ³rio pÃºblico no seu GitHub com o nome do seu usuÃ¡rio. O GitHub vai entender que esse repositÃ³rio possui um README especial de personalizaÃ§Ã£o e vai adicionar todas as alteraÃ§Ãµes no seu overview.

Criando o seu repositÃ³rio

Passo 2: Configurando seu GitHub actions
Antes de criar o seu workflow e adicionar o script, Ã© importante que vocÃª ative algumas permissÃµes que possivelmente estÃ£o desmarcadas no seu perfil.
Para alterar o que Ã© necessÃ¡rio, entre no repositÃ³rio que vocÃª criou e clique em settings > actions > general e ative as seguintes opÃ§Ãµes:
 

ğŸ”˜ allow all actions and reusable workflows

Configurando actions - 1
 
ğŸ”˜ read and write permissions

Configurando actions - 2

Passo 3: Criando o seu workflow
Agora que temos todas as permissÃµes ativadas, vamos adicionar o script para gerar os arquivos necessÃ¡rios.
No seu repositÃ³rio, clique em actions > new workflow e por fim clique em configurar simple workflow.

criando workflow

Quando vocÃª clicar vai abrir uma caixa de cÃ³digo, e Ã© lÃ¡ que vamos adicionar o nosso script! Apague todo o conteÃºdo predefinido e cole somente este:
name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: username #seu username
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Em #seu username coloque o seu nome de usuÃ¡rio no GitHub
alterando nome de usuÃ¡rio

ApÃ³s todo esse processo, altere o nome do documento e clique em start commit. Seu workflow jÃ¡ estÃ¡ pronto para uso! Para dar start no processo, basta ir em actions > generate datas > run workflow.

workflow start

Se esse checkbox (âœ…) aparecer, parabÃ©ns, vocÃª fez tudo certo!
 

Passo 4: Personalizando README.md
Para finalizar, vÃ¡ atÃ© o seu repositÃ³rio, clique no README.md e cole o seguinte comando (âš ï¸lembre-se de colocar o seu nome de usuÃ¡rio no comando):

![snake gif](https://github.com/SEU_USUARIO/SEU_REPOSITORIO/blob/output/github-contribution-grid-snake.svg)

Agora vocÃª jÃ¡ tÃªm a animaÃ§Ã£o devorando todos os seus commits! :D

ğŸ’š RepositÃ³rio do projeto Snake Game: Platane/snk
ğŸ–¤ Meu github: https://github.com/mariakarolinesvg

Top comments (3)

Subscribe
pic
Add to the discussion
 
 
felipemelogomes profile image
Felipe Melo
â€¢
Nov 10 '23

O meu nÃ£o funcionou.


1
 like
Like
Reply
 
 
vitoriaft profile image
VitÃ³ria de FÃ¡tima Teixeira
â€¢
Sep 18 '23

Consegui fazer e roda normalmente, porÃ©m nÃ£o mostra no meus commits


2
 likes
Like
Reply
 
 
thaisdn profile image
Thais-DN
â€¢
Feb 21

tem como trocar a cor da cobrinha?


1
 like
Like
Reply
Code of Conduct â€¢ Report abuse
profile
Arm
PROMOTED

Image of Arm event

Learn How Ruth Amos Supercharges Developer Creativity
ğŸ§’ğŸ½ Tap into your child-inspired creativity.
ğŸ¤ Embrace fearless problem-solving.
ğŸ’¡ Create ground-breaking solutions.
ğŸ”‘ Level up your design and development skills.
ğŸ† Learn from an award-winning engineer and innovator.

Register Now

Read next
afrozansenjuti profile image
Handling External JS Files in a React Website
Afroza Nowshin - Feb 4

vromanov profile image
Deploying Your First Pod in Kubernetes
Vladimir Romanov - Feb 13

nguhprince profile image
Flask tutorial: A student project recorder
Prince - Jan 22

anmolbaranwal profile image
12 things you didn't know you could do with Nextjs
Anmol Baranwal - Feb 20


Karol
Follow
ğŸ’œMaterializando ideias em cÃ³digos desde 2019!
EDUCATION
Instituto Federal de EducaÃ§Ã£o, CiÃªncia e Tecnologia.
JOINED
Mar 28, 2023
Trending on DEV Community 
uliyahoo profile image
How to build: an AI-powered PowerPoint generator (Next.js, OpenAI, CopilotKit)
#webdev #tutorial #programming #javascript
Shuttle profile image
Implementing API Rate Limiting in Rust
#rust #webdev #programming #tutorial
peckjon profile image
New year, new planning habits: using GitHub Projects to track your goals
#github #projectmanagement #team #tutorial
profile
Arm
PROMOTED

Image of Arm event

Learn to Innovate Fearlessly with Ruth Amos
Unlock your creative potential with dare-to-dream lessons in innovation from Ruth Amos, an award-winning engineer and innovator. Learn how to create groundbreaking solutions, develop strong problem-solving skills, and drive innovation at work. 

Register Now

name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: abdulrahmannadap #seu username
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
